//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageRecords
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Count { get; set; }
        public string generalPrice { get; set; }
        public string Category { get; set; }
        public bool status { get; set; }
    }
}
