//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string InventoryNumber { get; set; }
        public Nullable<System.DateTime> DateReceive { get; set; }
        public Nullable<System.DateTime> DateMoving { get; set; }
        public string Garanty { get; set; }
        public string Price { get; set; }
        public string WorkshopNumber { get; set; }
        public bool status { get; set; }
        public Nullable<System.DateTime> DateDeletion { get; set; }
        public Nullable<bool> editingWorkshop { get; set; }
    }
}
